[template]
src   = "nginx.conf"
dest  = "/opt/nginx/conf/nginx.conf"
uid = 0
gid = 0
mode  = "0644"
keys = [
  "/deis/config",
  "/deis/services",
  "/deis/router",
  "/deis/domains",
  "/deis/controller",
  "/deis/builder",
  "/deis/store/gateway",
  "/deis/certs",
]
check_cmd  = "check {{ .src }}"
reload_cmd = "/opt/nginx/sbin/nginx -s reload"
